# Generated by Django 6.0 on 2026-07-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('cotton', 'Хлопок'), ('microfiber', 'Микрофибра'), ('linen', 'Лен'), ('mixed', 'Смешанный')], max_length=50, null=True, verbose_name='Материал'),
        ),
    ]
